```{r}
library(tidymodels)
library(tidyverse)
library(lubridate)
library(stacks)
library(vip)
library(here)
```

```{r}
parks <- read_csv(here("data", "park_dimensions.csv")) |>
  pivot_longer(contains("F_"), names_to = "name", values_to = "length") |>
  mutate(
    bearing = case_when(
      str_detect(name, "LF") ~ "left",
      str_detect(name, "RF") ~ "right",
      str_detect(name, "CF") ~ "center",
      TRUE ~ name
    ),
    type = str_match(name, "\\w\\w_(.*)")[, 2]
  ) |>
  select(-name, -NAME) |>
  group_by(park, bearing) |>
  pivot_wider(c("park", "bearing", "Cover"), names_from = "type", values_from = "length")

df <- read_csv(here("data", "train.csv")) |>
  mutate(is_home_run = as.factor(is_home_run)) |>
  left_join(parks, by = c("park", "bearing"))

df
```

```{r}
set.seed(8291)
split <- initial_split(df, strata = "is_home_run")
train <- training(split)
test <- testing(split)

folds <- vfold_cv(train, v = 5)
mset <- metric_set(mn_log_loss)
controls <- control_grid(
  save_workflow = TRUE,
  save_pred = TRUE,
  verbose = TRUE
)
```

```{r}
no_hr <- test |>
  filter(!(bb_type %in% c("fly_ball", "line_drive"))) |>
  mutate(is_home_run = 0) |>
  select(bip_id, is_home_run)

test <- test |>
  filter(bb_type %in% c("fly_ball", "line_drive"))

train <- train |>
  filter(bb_type %in% c("fly_ball", "line_drive"))
```

We only care about fly balls and line drives

```{r}
workflow() |>
  add_model(null_model()) |>
  add_recipe(recipe(is_home_run ~ ., data = train) |>
    step_mutate(is_home_run = as.factor(is_home_run), skip = TRUE)) |>
  fit(train) |>
  augment(test) |>
  with(mn_log_loss_vec(as.factor(is_home_run), .pred_0))
```

Naive: 0.340

```{r}
rec <- recipe(is_home_run ~ ., data = train) |>
  step_mutate(
    month = month(game_date),
    home = home_team == batter_team,
    dist = launch_speed^2 * sin(launch_angle * pi / 180) * cos(launch_angle * pi / 180) * 0.44704^2 * 2 / 9.81,
    delta = dist - Dim * 0.3048,
  ) |>
  step_rm(bip_id, batter_id, pitcher_id, game_date, park, home_team, dist, Dim, contains("_name"), contains("_team")) |> 
  step_impute_mode(all_nominal_predictors()) |> 
  step_dummy(all_nominal_predictors()) |> 
  step_impute_median(all_numeric_predictors())

rec |>
  prep() |>
  juice() |> 
  map(~ sum(is.na(.x)))
```

```{r}
model <- boost_tree(mode = "classification",
                    trees = tune(),
                    mtry = tune(),
                    learn_rate = tune())


res <- workflow() |> 
  add_recipe(rec) |> 
  add_model(model) |> 
  tune_grid(folds, metrics = mset, control = controls, grid = crossing(
    learn_rate = 10^seq(-5,-1, length.out = 5),
    trees = floor(seq(200, 1000, length.out = 5)),
    mtry = c(3,5,7)
  ))

collect_metrics(res)

res |> 
  extract_fit_engine() |> 
  vip(n = 50)
```

CV: 0.099

